export enum Path {
  Root = '/',
  Login = '/login',
  Forgot = '/forgot',
  Register = '/registration',
  NewPassword = '/set-new-password',
  Profile = '/profile',
  PacksList = '/packslist',
  Pack = '/pack',
  Page404 = 'page404',
  Other = '*',
  Id = ':id',
  Token = ':token',
  Learn = '/learn',
}
